name: ipycytoscape
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.6
  - matplotlib-base
  - networkx
  - pandas
  - traitlets
  - spectate
  - py2neo
  - monotonic
  - ipywidgets=7
  - nodejs=18
